hhpc_subset$Sub_metering_1 <- as.numeric(hhpc_subset$Sub_metering_1)
plot(hhpc_subset$Date.Time, hhpc_subset$Sub_metering_1, type = "l", xlab ="", ylab = "Energy sub metering")
hhpc_subset$Sub_metering_2 <- as.numeric(hhpc_subset$Sub_metering_2)
lines(hhpc_subset$Date.Time, hhpc_subset$Sub_metering_2, col = "red")
lines(hhpc_subset$Date.Time, hhpc_subset$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty =c(1,1,1), col = c("black", "red", "blue"))
